export const getActivationEmailHTML = (activationUrl) => {
    return `<div style="font-family: Arial, sans-serif; padding: 20px; background: #f5f5f5;"><div style="max-width: 500px; margin: auto; background: #ffffff; padding: 20px; border-radius: 8px;"><h2 style="text-align: center; color: #333;">Welcome to Our Live Media Sharing 🎉</h2><p style="font-size: 16px; color: #444;">You're almost there! Click the button below to activate your account.</p><div style="text-align: center; margin: 30px 0;"><a href="${activationUrl}"style="background: #4CAF50; color: white; padding: 12px 20px;text-decoration: none; border-radius: 5px; font-weight: bold;">Activate Account</a></div><p style="font-size: 14px; color: #666;">Or copy and paste this link into your browser:</p><p style="word-break: break-all; color: #007BFF;">${activationUrl}</p><hr style="margin: 20px 0; border: none; border-top: 1px solid #ddd;" /><p style="font-size: 12px; color: #888; text-align: center;"> This link is valid for 10 minutes.</br>You can only request for activation three times a day.</br>If you did not create this account, you can safely ignore this email.</p></div></div>`;
};

export const getReactivationEmailHTML = (activationUrl) => {
    return `<div style="font-family: Arial, sans-serif; padding: 20px; background: #f5f5f5;"><div style="max-width: 500px; margin: auto; background: #ffffff; padding: 20px; border-radius: 8px;"><h2 style="text-align: center; color: #333;">Activate Your Account 🔄</h2><p style="font-size: 16px; color: #444;">Here's your new activation link. Click the button below to complete your registration.</p><div style="text-align: center; margin: 30px 0;"><a href="${activationUrl}"style="background: #4CAF50; color: white; padding: 12px 20px;text-decoration: none; border-radius: 5px; font-weight: bold;">Activate Account</a></div><p style="font-size: 14px; color: #666;">Or copy and paste this link into your browser:</p><p style="word-break: break-all; color: #007BFF;">${activationUrl}</p><hr style="margin: 20px 0; border: none; border-top: 1px solid #ddd;" /><p style="font-size: 12px; color: #888; text-align: center;">This link is valid for 10 minutes.</br>You can only request for activation three times a day.</br></br>If you did not request this, you can safely ignore this email.</p></div></div>`;
};

export const getPasswordResetEmailHTML = (resetUrl) => {
    return `<div style="font-family: Arial, sans-serif; padding: 20px; background: #f5f5f5;"><div style="max-width: 500px; margin: auto; background: #ffffff; padding: 20px; border-radius: 8px;"><h2 style="text-align: center; color: #333;">Reset Your Password 🔐</h2><p style="font-size: 16px; color: #444;">We received a request to reset your password. Click the button below to set a new one.</p><div style="text-align: center; margin: 30px 0;"><a href="${resetUrl}"style="background: #ff6b35; color: white; padding: 12px 20px;text-decoration: none; border-radius: 5px; font-weight: bold;">Reset Password</a></div><p style="font-size: 14px; color: #666;">Or copy and paste this link into your browser:</p><p style="word-break: break-all; color: #007BFF;">${resetUrl}</p><hr style="margin: 20px 0; border: none; border-top: 1px solid #ddd;" /><p style="font-size: 12px; color: #888; text-align: center;">This link is valid for 15 minutes.<br/>You can request a password reset up to three times a day.<br/>If you did not request this, you can safely ignore this email.</p></div></div>`;
};
